apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-play
spec:
  selector:
    matchLabels:
      app: hello-play
  replicas: 1
  template:
    metadata:
      labels:
        app: hello-play
    spec:
      containers:
      - name: hello-play
        image: 936422292136.dkr.ecr.eu-west-1.amazonaws.com/shopingapirepo
---
apiVersion: v1
kind: Service
metadata:
  name: hello-play
spec:
  selector:
    app: hello-play
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 9000
  type: LoadBalancer
  
